"""initial migration

Revision ID: 4bdedf222641
Revises: 
Create Date: 2024-11-19 16:21:07.923509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bdedf222641'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_client_document', ['document_type', 'document_number'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_document', ['document_type', 'document_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_document', type_='unique')

    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_constraint('uq_client_document', type_='unique')

    # ### end Alembic commands ###
